//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UWSaralServices.LABillingChangeService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/BO_BillingChange")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityBCHMOD", Namespace="http://schemas.datacontract.org/2004/07/BO_BillingChange")]
    [System.SerializableAttribute()]
    public partial class EntityBCHMOD : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContractNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContractNumber {
            get {
                return this.ContractNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ContractNumberField, value) != true)) {
                    this.ContractNumberField = value;
                    this.RaisePropertyChanged("ContractNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityBCHMET", Namespace="http://schemas.datacontract.org/2004/07/BO_BillingChange")]
    [System.SerializableAttribute()]
    public partial class EntityBCHMET : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BANKACCDSCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BANKACCOUNTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BANKKEYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BKCARDNUMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BNKACTYPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BranchField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CURRCODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarrierCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContractNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DATEFROMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DETLSUMMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DTEAPROVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> EFFDATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FACTHOUSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MANDAMTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MANDREFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MANDSTATField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MOPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SCTYCDEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TIMESUSEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserRoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZDDDAYField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BANKACCDSC {
            get {
                return this.BANKACCDSCField;
            }
            set {
                if ((object.ReferenceEquals(this.BANKACCDSCField, value) != true)) {
                    this.BANKACCDSCField = value;
                    this.RaisePropertyChanged("BANKACCDSC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BANKACCOUNT {
            get {
                return this.BANKACCOUNTField;
            }
            set {
                if ((object.ReferenceEquals(this.BANKACCOUNTField, value) != true)) {
                    this.BANKACCOUNTField = value;
                    this.RaisePropertyChanged("BANKACCOUNT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BANKKEY {
            get {
                return this.BANKKEYField;
            }
            set {
                if ((object.ReferenceEquals(this.BANKKEYField, value) != true)) {
                    this.BANKKEYField = value;
                    this.RaisePropertyChanged("BANKKEY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BKCARDNUM {
            get {
                return this.BKCARDNUMField;
            }
            set {
                if ((object.ReferenceEquals(this.BKCARDNUMField, value) != true)) {
                    this.BKCARDNUMField = value;
                    this.RaisePropertyChanged("BKCARDNUM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BNKACTYP {
            get {
                return this.BNKACTYPField;
            }
            set {
                if ((object.ReferenceEquals(this.BNKACTYPField, value) != true)) {
                    this.BNKACTYPField = value;
                    this.RaisePropertyChanged("BNKACTYP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Branch {
            get {
                return this.BranchField;
            }
            set {
                if ((object.ReferenceEquals(this.BranchField, value) != true)) {
                    this.BranchField = value;
                    this.RaisePropertyChanged("Branch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CURRCODE {
            get {
                return this.CURRCODEField;
            }
            set {
                if ((object.ReferenceEquals(this.CURRCODEField, value) != true)) {
                    this.CURRCODEField = value;
                    this.RaisePropertyChanged("CURRCODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CarrierCode {
            get {
                return this.CarrierCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CarrierCodeField, value) != true)) {
                    this.CarrierCodeField = value;
                    this.RaisePropertyChanged("CarrierCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContractNumber {
            get {
                return this.ContractNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ContractNumberField, value) != true)) {
                    this.ContractNumberField = value;
                    this.RaisePropertyChanged("ContractNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DATEFROM {
            get {
                return this.DATEFROMField;
            }
            set {
                if ((this.DATEFROMField.Equals(value) != true)) {
                    this.DATEFROMField = value;
                    this.RaisePropertyChanged("DATEFROM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DETLSUMM {
            get {
                return this.DETLSUMMField;
            }
            set {
                if ((object.ReferenceEquals(this.DETLSUMMField, value) != true)) {
                    this.DETLSUMMField = value;
                    this.RaisePropertyChanged("DETLSUMM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DTEAPROV {
            get {
                return this.DTEAPROVField;
            }
            set {
                if ((this.DTEAPROVField.Equals(value) != true)) {
                    this.DTEAPROVField = value;
                    this.RaisePropertyChanged("DTEAPROV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EFFDATE {
            get {
                return this.EFFDATEField;
            }
            set {
                if ((this.EFFDATEField.Equals(value) != true)) {
                    this.EFFDATEField = value;
                    this.RaisePropertyChanged("EFFDATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FACTHOUS {
            get {
                return this.FACTHOUSField;
            }
            set {
                if ((object.ReferenceEquals(this.FACTHOUSField, value) != true)) {
                    this.FACTHOUSField = value;
                    this.RaisePropertyChanged("FACTHOUS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MANDAMT {
            get {
                return this.MANDAMTField;
            }
            set {
                if ((this.MANDAMTField.Equals(value) != true)) {
                    this.MANDAMTField = value;
                    this.RaisePropertyChanged("MANDAMT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MANDREF {
            get {
                return this.MANDREFField;
            }
            set {
                if ((object.ReferenceEquals(this.MANDREFField, value) != true)) {
                    this.MANDREFField = value;
                    this.RaisePropertyChanged("MANDREF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MANDSTAT {
            get {
                return this.MANDSTATField;
            }
            set {
                if ((object.ReferenceEquals(this.MANDSTATField, value) != true)) {
                    this.MANDSTATField = value;
                    this.RaisePropertyChanged("MANDSTAT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MOP {
            get {
                return this.MOPField;
            }
            set {
                if ((object.ReferenceEquals(this.MOPField, value) != true)) {
                    this.MOPField = value;
                    this.RaisePropertyChanged("MOP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SCTYCDE {
            get {
                return this.SCTYCDEField;
            }
            set {
                if ((object.ReferenceEquals(this.SCTYCDEField, value) != true)) {
                    this.SCTYCDEField = value;
                    this.RaisePropertyChanged("SCTYCDE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Source {
            get {
                return this.SourceField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceField, value) != true)) {
                    this.SourceField = value;
                    this.RaisePropertyChanged("Source");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TIMESUSE {
            get {
                return this.TIMESUSEField;
            }
            set {
                if ((this.TIMESUSEField.Equals(value) != true)) {
                    this.TIMESUSEField = value;
                    this.RaisePropertyChanged("TIMESUSE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIDField, value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserRole {
            get {
                return this.UserRoleField;
            }
            set {
                if ((object.ReferenceEquals(this.UserRoleField, value) != true)) {
                    this.UserRoleField = value;
                    this.RaisePropertyChanged("UserRole");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZDDDAY {
            get {
                return this.ZDDDAYField;
            }
            set {
                if ((object.ReferenceEquals(this.ZDDDAYField, value) != true)) {
                    this.ZDDDAYField = value;
                    this.RaisePropertyChanged("ZDDDAY");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityResponse", Namespace="http://schemas.datacontract.org/2004/07/BO_BillingChange")]
    [System.SerializableAttribute()]
    public partial class EntityResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BORequestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BOResponseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.DataSet BOResponseDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BORequest {
            get {
                return this.BORequestField;
            }
            set {
                if ((object.ReferenceEquals(this.BORequestField, value) != true)) {
                    this.BORequestField = value;
                    this.RaisePropertyChanged("BORequest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BOResponse {
            get {
                return this.BOResponseField;
            }
            set {
                if ((object.ReferenceEquals(this.BOResponseField, value) != true)) {
                    this.BOResponseField = value;
                    this.RaisePropertyChanged("BOResponse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.DataSet BOResponseData {
            get {
                return this.BOResponseDataField;
            }
            set {
                if ((object.ReferenceEquals(this.BOResponseDataField, value) != true)) {
                    this.BOResponseDataField = value;
                    this.RaisePropertyChanged("BOResponseData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityBCHQUO", Namespace="http://schemas.datacontract.org/2004/07/BO_BillingChange")]
    [System.SerializableAttribute()]
    public partial class EntityBCHQUO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string clientNumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string clientNum {
            get {
                return this.clientNumField;
            }
            set {
                if ((object.ReferenceEquals(this.clientNumField, value) != true)) {
                    this.clientNumField = value;
                    this.RaisePropertyChanged("clientNum");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BillingChange", Namespace="http://schemas.datacontract.org/2004/07/BO_BillingChange")]
    [System.SerializableAttribute()]
    public partial class BillingChange : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApplicationNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BranchField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContractNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MandateReferenceNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartnerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PreferredDebitDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserRoleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicationNo {
            get {
                return this.ApplicationNoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicationNoField, value) != true)) {
                    this.ApplicationNoField = value;
                    this.RaisePropertyChanged("ApplicationNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Branch {
            get {
                return this.BranchField;
            }
            set {
                if ((object.ReferenceEquals(this.BranchField, value) != true)) {
                    this.BranchField = value;
                    this.RaisePropertyChanged("Branch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContractNo {
            get {
                return this.ContractNoField;
            }
            set {
                if ((object.ReferenceEquals(this.ContractNoField, value) != true)) {
                    this.ContractNoField = value;
                    this.RaisePropertyChanged("ContractNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MandateReferenceNo {
            get {
                return this.MandateReferenceNoField;
            }
            set {
                if ((object.ReferenceEquals(this.MandateReferenceNoField, value) != true)) {
                    this.MandateReferenceNoField = value;
                    this.RaisePropertyChanged("MandateReferenceNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartnerID {
            get {
                return this.PartnerIDField;
            }
            set {
                if ((object.ReferenceEquals(this.PartnerIDField, value) != true)) {
                    this.PartnerIDField = value;
                    this.RaisePropertyChanged("PartnerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PreferredDebitDate {
            get {
                return this.PreferredDebitDateField;
            }
            set {
                if ((object.ReferenceEquals(this.PreferredDebitDateField, value) != true)) {
                    this.PreferredDebitDateField = value;
                    this.RaisePropertyChanged("PreferredDebitDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Source {
            get {
                return this.SourceField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceField, value) != true)) {
                    this.SourceField = value;
                    this.RaisePropertyChanged("Source");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIDField, value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserRole {
            get {
                return this.UserRoleField;
            }
            set {
                if ((object.ReferenceEquals(this.UserRoleField, value) != true)) {
                    this.UserRoleField = value;
                    this.RaisePropertyChanged("UserRole");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BillingChangeResponse", Namespace="http://schemas.datacontract.org/2004/07/BO_BillingChange")]
    [System.SerializableAttribute()]
    public partial class BillingChangeResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContractNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MandateReferenceNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContractNo {
            get {
                return this.ContractNoField;
            }
            set {
                if ((object.ReferenceEquals(this.ContractNoField, value) != true)) {
                    this.ContractNoField = value;
                    this.RaisePropertyChanged("ContractNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MandateReferenceNo {
            get {
                return this.MandateReferenceNoField;
            }
            set {
                if ((object.ReferenceEquals(this.MandateReferenceNoField, value) != true)) {
                    this.MandateReferenceNoField = value;
                    this.RaisePropertyChanged("MandateReferenceNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LABillingChangeService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        UWSaralServices.LABillingChangeService.CompositeType GetDataUsingDataContract(UWSaralServices.LABillingChangeService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<UWSaralServices.LABillingChangeService.CompositeType> GetDataUsingDataContractAsync(UWSaralServices.LABillingChangeService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BO_BCHMOD", ReplyAction="http://tempuri.org/IService1/BO_BCHMODResponse")]
        void BO_BCHMOD(UWSaralServices.LABillingChangeService.EntityBCHMOD BCHEntity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BO_BCHMOD", ReplyAction="http://tempuri.org/IService1/BO_BCHMODResponse")]
        System.Threading.Tasks.Task BO_BCHMODAsync(UWSaralServices.LABillingChangeService.EntityBCHMOD BCHEntity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BO_BCHMET", ReplyAction="http://tempuri.org/IService1/BO_BCHMETResponse")]
        UWSaralServices.LABillingChangeService.EntityResponse BO_BCHMET(UWSaralServices.LABillingChangeService.EntityBCHMET BCHEntity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BO_BCHMET", ReplyAction="http://tempuri.org/IService1/BO_BCHMETResponse")]
        System.Threading.Tasks.Task<UWSaralServices.LABillingChangeService.EntityResponse> BO_BCHMETAsync(UWSaralServices.LABillingChangeService.EntityBCHMET BCHEntity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BO_BCHQUO", ReplyAction="http://tempuri.org/IService1/BO_BCHQUOResponse")]
        void BO_BCHQUO(UWSaralServices.LABillingChangeService.EntityBCHQUO BCHEntity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BO_BCHQUO", ReplyAction="http://tempuri.org/IService1/BO_BCHQUOResponse")]
        System.Threading.Tasks.Task BO_BCHQUOAsync(UWSaralServices.LABillingChangeService.EntityBCHQUO BCHEntity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BillingChange", ReplyAction="http://tempuri.org/IService1/BillingChangeResponse")]
        UWSaralServices.LABillingChangeService.BillingChangeResponse BillingChange([System.ServiceModel.MessageParameterAttribute(Name="BillingChange")] UWSaralServices.LABillingChangeService.BillingChange BillingChange1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BillingChange", ReplyAction="http://tempuri.org/IService1/BillingChangeResponse")]
        System.Threading.Tasks.Task<UWSaralServices.LABillingChangeService.BillingChangeResponse> BillingChangeAsync(UWSaralServices.LABillingChangeService.BillingChange BillingChange);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : UWSaralServices.LABillingChangeService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<UWSaralServices.LABillingChangeService.IService1>, UWSaralServices.LABillingChangeService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public UWSaralServices.LABillingChangeService.CompositeType GetDataUsingDataContract(UWSaralServices.LABillingChangeService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<UWSaralServices.LABillingChangeService.CompositeType> GetDataUsingDataContractAsync(UWSaralServices.LABillingChangeService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public void BO_BCHMOD(UWSaralServices.LABillingChangeService.EntityBCHMOD BCHEntity) {
            base.Channel.BO_BCHMOD(BCHEntity);
        }
        
        public System.Threading.Tasks.Task BO_BCHMODAsync(UWSaralServices.LABillingChangeService.EntityBCHMOD BCHEntity) {
            return base.Channel.BO_BCHMODAsync(BCHEntity);
        }
        
        public UWSaralServices.LABillingChangeService.EntityResponse BO_BCHMET(UWSaralServices.LABillingChangeService.EntityBCHMET BCHEntity) {
            return base.Channel.BO_BCHMET(BCHEntity);
        }
        
        public System.Threading.Tasks.Task<UWSaralServices.LABillingChangeService.EntityResponse> BO_BCHMETAsync(UWSaralServices.LABillingChangeService.EntityBCHMET BCHEntity) {
            return base.Channel.BO_BCHMETAsync(BCHEntity);
        }
        
        public void BO_BCHQUO(UWSaralServices.LABillingChangeService.EntityBCHQUO BCHEntity) {
            base.Channel.BO_BCHQUO(BCHEntity);
        }
        
        public System.Threading.Tasks.Task BO_BCHQUOAsync(UWSaralServices.LABillingChangeService.EntityBCHQUO BCHEntity) {
            return base.Channel.BO_BCHQUOAsync(BCHEntity);
        }
        
        public UWSaralServices.LABillingChangeService.BillingChangeResponse BillingChange(UWSaralServices.LABillingChangeService.BillingChange BillingChange1) {
            return base.Channel.BillingChange(BillingChange1);
        }
        
        public System.Threading.Tasks.Task<UWSaralServices.LABillingChangeService.BillingChangeResponse> BillingChangeAsync(UWSaralServices.LABillingChangeService.BillingChange BillingChange) {
            return base.Channel.BillingChangeAsync(BillingChange);
        }
    }
}
